apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "5"
    deployment.kubernetes.io/max-replicas: "7"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-07-19T21:48:20Z"
  generation: 1
  labels:
    app: webapp
    pod-template-hash: 5654c984c
  name: webapp-5654c984c
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: webapp
    uid: bda5c74d-b9b5-4bda-a8a3-4be46dfb6ceb
  resourceVersion: "374524"
  uid: efc0293e-7d46-4603-99e0-73a3c9713bc0
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
      pod-template-hash: 5654c984c
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
        pod-template-hash: 5654c984c
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  fullyLabeledReplicas: 5
  observedGeneration: 1
  readyReplicas: 5
  replicas: 5
