apiVersion: v1
kind: Pod
metadata:
 name: nginx
 creationTimestamp: null
 labels:
  run: nginx
  name: nginx
spec:
 containers:
 - image: nginx
   name: nginx
   resources: {}
 dnsPolicy: ClusterFirst
 restartPolicy: Never
 nodeSelector: 
  nodeName: nginxnode
status: {}