apiVersion: v1
kind: Pod
metadata:
 name: nginx-resolver
 labels:
  app: nginx
spec:
 containers:
 - name: nginx-resolver
   image: nginx
   ports:
   - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
 name: nginx-resolver-service
spec:
 ports:
 - name: http
   protocol: TCP
   port: 80
   targetPort: 80
 selector:
  app: nginx
